# Generated by Django 3.2.9 on 2021-12-09 01:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='背景色')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='投稿者')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('main_text', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('created_at', models.DateField(auto_now=True, verbose_name='作成日')),
                ('color', models.CharField(choices=[('#ffffff', '白'), ('#000000', '黒')], default='#ffffff', max_length=7, verbose_name='文字色')),
                ('tag', models.ManyToManyField(to='card.TagModel', verbose_name='タグ')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
