# Generated by Django 3.2.9 on 2021-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='username',
            field=models.CharField(max_length=100, verbose_name='投稿者'),
        ),
    ]
