# Generated by Django 3.2.9 on 2021-12-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_articlemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='username',
        ),
    ]
